src/Entity/Blogpost.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\BlogpostRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BlogpostRepository::class)
 */
class Blogpost
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Images", mappedBy="blogpost",cascade={"persist"})
     */
    private $images;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Status=false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->created_at = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setBlogpost($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getBlogpost() === $this) {
                $image->setBlogpost(null);
            }
        }
        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->Status;
    }

    public function setStatus(bool $Status): self
    {
        $this->Status = $Status;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Entity/Environnement.php
<?php

namespace App\Entity;

use App\Repository\EnvironnementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EnvironnementRepository::class)
 */
class Environnement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Region;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Theme;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Number_phone;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Images", mappedBy="environnement",cascade={"persist"})
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=Options::class, inversedBy="environnements",cascade={"persist"})
     */
    private $Options;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setEnvironnement($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getEnvironnement() === $this) {
                $image->setEnvironnement(null);
            }
        }
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->Region;
    }

    public function setRegion(string $Region): self
    {
        $this->Region = $Region;

        return $this;
    }

    public function getTheme(): ?string
    {
        return $this->Theme;
    }

    public function setTheme(string $Theme): self
    {
        $this->Theme = $Theme;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(?string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getNumberPhone(): ?string
    {
        return $this->Number_phone;
    }

    public function setNumberPhone(?string $Number_phone): self
    {
        $this->Number_phone = $Number_phone;

        return $this;
    }

    public function getOptions(): ?Options
    {
        return $this->Options;
    }

    public function setOptions(?Options $Options): self
    {
        $this->Options = $Options;

        return $this;
    }
}

src/Entity/Host.php
<?php

namespace App\Entity;

use App\Repository\HostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=HostRepository::class)
 */
class Host
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $superficy;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_of_people = false;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2)
     */
    private $price_for_options;

    /**
     * @ORM\Column(type="boolean")
     */
    private $forTents = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $forCaravans = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $forVans = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $forCars = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $forMotorcycles = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Country = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Mountain = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Sea = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $City = false;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Lake = false;

    /**
     * @ORM\Column(type="text")
     */
    private $Summarise;

    /**
     * @ORM\Column(type="text")
     */
    private $The_Setting;

    /**
     * @ORM\Column(type="text")
     */
    private $The_Sanitary_Facilities;

    /**
     * @ORM\Column(type="text")
     */
    private $The_Equipement;

   
    /**
     * @ORM\Column(type="boolean")
     */
    private $Loan = false ;

    /**
     * @ORM\Column(type="text")
     */
    private $Other_Remarks;

    /**
     * @ORM\Column(type="text")
     */
    private $Rules_of_the_field;

    /**
     * @ORM\Column(type="text")
     */
    private $the_pitches;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $price_of_location;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $region;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Images", mappedBy="host",cascade={"persist"})
     */
    private $images;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToOne(targetEntity=Options::class, inversedBy="hosts",cascade={"persist"})
     */
    private $Options;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="Host")
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="hosts")
     */
    private $User;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->options = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setHost($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getHost() === $this) {
                $image->setHost(null);
            }
        }
        return $this;
    }


    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getSuperficy(): ?int
    {
        return $this->superficy;
    }

    public function setSuperficy(int $superficy): self
    {
        $this->superficy = $superficy;

        return $this;
    }

    public function getNumberOfPeople(): ?int
    {
        return $this->number_of_people;
    }

    public function setNumberOfPeople(int $number_of_people): self
    {
        $this->number_of_people = $number_of_people;

        return $this;
    }

    public function getPriceForOptions(): ?string
    {
        return $this->price_for_options;
    }

    public function setPriceForOptions(float $price_for_options): self
    {
        $this->price_for_options = $price_for_options;

        return $this;
    }

    public function getForTents(): ?bool
    {
        return $this->forTents;
    }

    public function setForTents(bool $forTents): self
    {
        $this->forTents = $forTents;

        return $this;
    }

    public function getForCaravans(): ?bool
    {
        return $this->forCaravans;
    }

    public function setForCaravans(bool $forCaravans): self
    {
        $this->forCaravans = $forCaravans;

        return $this;
    }

    public function getForVans(): ?bool
    {
        return $this->forVans;
    }

    public function setForVans(bool $forVans): self
    {
        $this->forVans = $forVans;

        return $this;
    }

    public function getForCars(): ?bool
    {
        return $this->forCars;
    }

    public function setForCars(bool $forCars): self
    {
        $this->forCars = $forCars;

        return $this;
    }

    public function getForMotorcycles(): ?bool
    {
        return $this->forMotorcycles;
    }

    public function setForMotorcycles(bool $forMotorcycles): self
    {
        $this->forMotorcycles = $forMotorcycles;

        return $this;
    }

    public function getCountry(): ?bool
    {
        return $this->Country;
    }

    public function setCountry(bool $Country): self
    {
        $this->Country = $Country;

        return $this;
    }

    public function getMountain(): ?bool
    {
        return $this->Mountain;
    }

    public function setMountain(bool $Mountain): self
    {
        $this->Mountain = $Mountain;

        return $this;
    }

    public function getSea(): ?bool
    {
        return $this->Sea;
    }

    public function setSea(bool $Sea): self
    {
        $this->Sea = $Sea;

        return $this;
    }

    public function getCity(): ?bool
    {
        return $this->City;
    }

    public function setCity(bool $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getLake(): ?bool
    {
        return $this->Lake;
    }

    public function setLake(bool $Lake): self
    {
        $this->Lake = $Lake;

        return $this;
    }

    public function getSummarise(): ?string
    {
        return $this->Summarise;
    }

    public function setSummarise(string $Summarise): self
    {
        $this->Summarise = $Summarise;

        return $this;
    }

    public function getTheSetting(): ?string
    {
        return $this->The_Setting;
    }

    public function setTheSetting(string $The_Setting): self
    {
        $this->The_Setting = $The_Setting;

        return $this;
    }

    public function getTheSanitaryFacilities(): ?string
    {
        return $this->The_Sanitary_Facilities;
    }

    public function setTheSanitaryFacilities(string $The_Sanitary_Facilities): self
    {
        $this->The_Sanitary_Facilities = $The_Sanitary_Facilities;

        return $this;
    }

    public function getTheEquipement(): ?string
    {
        return $this->The_Equipement;
    }

    public function setTheEquipement(string $The_Equipement): self
    {
        $this->The_Equipement = $The_Equipement;

        return $this;
    }

    public function getLoan(): ?bool
    {
        return $this->Loan;
    }

    public function setLoan(bool $Loan): self
    {
        $this->Loan = $Loan;

        return $this;
    }

    public function getOtherRemarks(): ?string
    {
        return $this->Other_Remarks;
    }

    public function setOtherRemarks(string $Other_Remarks): self
    {
        $this->Other_Remarks = $Other_Remarks;

        return $this;
    }

    public function getRulesOfTheField(): ?string
    {
        return $this->Rules_of_the_field;
    }

    public function setRulesOfTheField(string $Rules_of_the_field): self
    {
        $this->Rules_of_the_field = $Rules_of_the_field;

        return $this;
    }

    public function getThePitches(): ?string
    {
        return $this->the_pitches;
    }

    public function setThePitches(string $the_pitches): self
    {
        $this->the_pitches = $the_pitches;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPriceOfLocation(): ?string
    {
        return $this->price_of_location;
    }

    public function setPriceOfLocation(string $price_of_location): self
    {
        $this->price_of_location = $price_of_location;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->region;
    }

    public function setRegion(string $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getOptions(): ?Options
    {
        return $this->Options;
    }

    public function setOptions(?Options $Options): self
    {
        $this->Options = $Options;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {

src/Controller/HomepageController.php
<?php

namespace App\Controller;

use App\Repository\BlogpostRepository;
use App\Repository\EnvironnementRepository;
use App\Repository\HostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomepageController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     */
    public function index(HostRepository $hostRepository, BlogpostRepository $blogpostRepository, EnvironnementRepository $environnementRepository): Response
    {   $blogpost = $blogpostRepository->findBy([],['created_at'=>'DESC'], 3, 0);
        return $this->render('homepage/index.html.twig', [
            'controller_name' => 'HomepageController',
            'hosts' => $hostRepository->findAll(),
            'blogposts' => $blogpost,
            'environnements' => $environnementRepository->findAll(),
        ]);
    }


}

templates/homepage/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Bienvenue - CampinGarden{% endblock %}

{% block body %}

    <div class="head row d-flex">
        <div class="title">
            <h1>"Dans un voyage ce n'est pas la destination qui compte mais toujours le chemin parcouru et les détours surtout"</h1>
            <small>Bienvenue sur CampinGarden</small>
        </div>
        <div class="search">
            <h3>Vous souhaitez partir? Recherchez ici dans les villes qui vous intéressent</h3>
            <div class="input-group" id="search-input">
                <div class="form-outline">
                    <input type="search" id="form1" class="form-control" placeholder="Search..."/>
                </div>
                <button type="button" class="btn btn-info">
                    <i class="ri-search-line"></i> Recherchez
                </button>
            </div>
        </div>
    </div>


<div class="popular text-center">
    <h3>Météo</h3>
    <hr class="style1">
</div>
<br>
<div class="container d-flex justify-content-around align-items-center">

            <form>
                <div class="form-groupe">
                    <input type="text" class="form-control" id='inputcity'/>
                </div>

                <button type="submit" class="btn btn-info btn-block">Rechercher</button>
            </form>
    <br>
                <div id="city" class="box"></div>
                <div id="temp" class="box"></div>
                <div id="humidity" class="box"></div>
                <div id="wind" class="box"></div>

</div>
    <div class="popular_content col-12" style="max-width: 80vw; margin-left: auto; margin-right: auto;">
        <div class="popular text-center">
            <h3>Destinations Récentes</h3>
            <hr class="style1">
        </div>
        <br>
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" style="max-width: 80vw; margin-left: auto; margin-right: auto">
                {% for host in hosts %}
                <div {% if loop.index0 == 0 %} class="carousel-item active" {% else %} class="carousel-item" {% endif %}">
                <div class="card mb-3">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            {% for image in host.images %}
                                {% for image in host.images %}
                                    <div>
                                        <img src="{{ asset('/uploads/'~image.name) }}" alt="{{ host.title }}" width="95%">
                                    </div>
                                {% endfor %}
                            {% endfor %}
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ host.title }}</h5>
                                <p class="card-text">{{ host.summarise | slice(0, 150)}}</p>
                                <p class="card-text">Situé en {{ host.region }}</p>
                                <br>
                                <hr>
                                <br>
                                <p class="card-text">Vous souhaitez réserver ce terrain? N'hésitez plus, contactez l'hôte</p>
                                <a class="btn btn-info" href="{{ path('host_show', {'id': host.id}) }}">Voir l'hote</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <a href="{{ path('host_host') }}">Voir toutes les destinations</a>
        <br>
        <br>
        <br>
        <br>
    </div>

    <section class="jumbotron text-center newsletter" style="margin-left: auto; margin-right: auto">
        <div class="container">
            <h1>Pour recevoir notre Newsletter</h1>
            <div class="input-group" id="search-input">
                <div class="form-outline">
                    <input type="search" id="form1" class="form-control" placeholder="Entrez votre Email"/>
                </div>
                <button type="button" class="btn btn-info">Valider l'email</button>
            </div>
        </div>
    </section>
<br>
<br>
    <div class="popular text-center">
        <h3>Lieux à visiter Récents</h3>
        <hr class="style1">
    </div>
    <br>
    <div id="carouselExample" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner" style="max-width: 80vw; margin-left: auto; margin-right: auto">
            {% for environnement in environnements %}
                <div {% if loop.index0 == 0 %} class="carousel-item active" {% else %} class="carousel-item" {% endif %}">
                    <div class="card mb-3">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                {% for image in environnement.images %}
                                    {% for image in environnement.images %}
                                        <div>
                                            <img src="{{ asset('/uploads/'~image.name) }}" alt="" width="100%">
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ environnement.title }}</h5>
                                    <p class="card-text">{{ environnement.description | slice(0, 300)}}</p>
                                    <p class="card-text">Situé en {{ environnement.region }}</p>
                                    <br>
                                    <hr>
                                    <br>
                                    <p class="card-text">Vous souhaitez réserver ce terrain? N'hésitez plus, contactez l'hôte</p>
                                    <a class="btn btn-info" href="{{ path('environnement_show', {'id': environnement.id}) }}">Voir le lieu</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExample" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    <a href="{{ path('host_host') }}">Voir tous les lieux à visiter</a>
    <br>
    <br>
    </div>
    </div>
    <div class="popular text-center">
        <h3>Besoin de conseil?</h3>
        <br>
        <hr class="style1">
        <br>
        <h4>Faites un tour sur notre blog</h4>
        <br>
        <a href="{{ path('blogpost_blog') }}">Voir le blog</a>
        <br>
    </div>
    <div class="popular_content" style="max-width: 80vw; margin-left: auto; margin-right: auto">
        <div class="album text-center">
            <div class="row">
                    {% for blogpost in blogposts %}
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                {% for image in blogpost.images %}
                                    {% for image in blogpost.images %}
                                        <img class="bd-placeholder-img card-img-top" width="100%" height="225" src="{{ asset('/uploads/'~image.name) }}" alt="{{ blogpost.title }}">
                                    {% endfor %}
                                {% endfor %}
                                <div class="card-body">
                                    <h4 class="card-title">{{ blogpost.title | slice(0, 20)}}</h4>
                                    <p class="card-text">{{ blogpost.content | slice(0, 80)}}...</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a class="btn btn-info" href="{{ path('blogpost_show', {'id': blogpost.id}) }}">Voir l'article</a>
                                        </div>
                                        <small class="text-muted">Crée le {{ blogpost.createdAt ? blogpost.createdAt|date('d-m-Y') : '' }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
            </div>
    </div>



{% endblock %}