src/Entity/Environnement.php
<?php

namespace App\Entity;

use App\Repository\EnvironnementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EnvironnementRepository::class)
 */
class Environnement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Region;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Theme;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Number_phone;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Images", mappedBy="environnement",cascade={"persist"})
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=Options::class, inversedBy="environnements",cascade={"persist"})
     */
    private $Options;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setEnvironnement($this);
        }

        return $this;
    }

    public function removeImage(Images $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getEnvironnement() === $this) {
                $image->setEnvironnement(null);
            }
        }
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getRegion(): ?string
    {
        return $this->Region;
    }

    public function setRegion(string $Region): self
    {
        $this->Region = $Region;

        return $this;
    }

    public function getTheme(): ?string
    {
        return $this->Theme;
    }

    public function setTheme(string $Theme): self
    {
        $this->Theme = $Theme;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(?string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getNumberPhone(): ?string
    {
        return $this->Number_phone;
    }

    public function setNumberPhone(?string $Number_phone): self
    {
        $this->Number_phone = $Number_phone;

        return $this;
    }

    public function getOptions(): ?Options
    {
        return $this->Options;
    }

    public function setOptions(?Options $Options): self
    {
        $this->Options = $Options;

        return $this;
    }
}

src/Form/EnvironnementType.php
<?php

namespace App\Form;

use App\Entity\Environnement;
use Symfony\Component\Console\Color;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\ColorType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EnvironnementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title', TextType::class, array(
                "label"=>"Titre",))

            ->add('Region', ChoiceType::class,[
                    'label'=>"Indiquez la région  ", 'choices'=>[
                    'Auvergne-Rhône-Alpes'=>"Auvergne-Rhône-Alpes",
                    'Bourgogne-Franche-Comté'=>"Bourgogne-Franche-Comté",
                    'Bretagne'=>"Bretagne",
                    'Centre-Val de Loires'=>"Centre-Val de Loire",
                    'Corse'=>"Corse",
                    'Grand Est'=>"Grand Est",
                    'Hauts-de-France'=>"Hauts-de-France",
                    'Ile-de-France'=>"Ile-de-Frances",
                    'Normandie'=>"Normandie",
                    'Nouvelle-Aquitaine'=>"Nouvelle-Aquitaine",
                    'Occitanie'=>"Occitanie",
                    'Pays de la Loire'=>"Pays de la Loire",
                    'Provence-Alpes-Côte d’Azur'=>"Provence-Alpes-Côte d’Azur",
                ]
            ])
            ->add('Theme', ChoiceType::class,[
                    'label'=>"Indiquez le thème du lieu ",'choices'=>[
                    'Chateaux' => 'Chateaux',
                    'Lieux Historiques' => 'Lieux Historiques',
                    'Vignerons' => 'Vignerons',
                    'Artisanat' => 'Artisanat',
                    'Cyclotourisme' => 'Cyclotourisme',
                    'En famille' => 'En famille',
                    'Bien-être' => 'Bien-être',
                    'Ferme' => 'Ferme',
                    'Bord de mer' => 'Bord de mer',
                    'Randonnees' => 'Randonnees',
                    'Parcs zoologiques' => 'Parcs zoologiques',
                    'Parcs de loisirs' => 'Parcs de loisirs',
                ]
            ])
            ->add('Description', TextareaType::class,[
                'label'=>"Description",
                'attr'=>[
                'placeholder'=>"Saisissez la description du lieu"
                ]
            ])
            ->add('Adresse', TextareaType::class,[
                'label'=>"Adresse",
                'attr'=>[
                'placeholder'=>"Saisissez l'adresse du lieu"
                ],
                'help'=>"L'adresse n'est pas obligatoire.",
                'required'=>false,
            ])


            ->add('Number_phone', TelType::class,[
                'label'=>"Numéro de téléphone",
                'attr'=>[
                'placeholder'=>"Saisissez votre numéro de téléphone"
                ],
                'help'=>"Le numéro de téléphone n'est pas obligatoire.",
                'help_attr'=>[
                    'class'=>"important"
                ],
                'required'=>false,
            ])

            ->add('images', FileType::class,[
                'label' => false,
                'multiple' => true,
                'mapped' => false,
                'required' => false
            ])

            ->add('Options',OptionsType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Environnement::class,
        ]);
    }
}

src/Controller/EnvironnementController.php
<?php

namespace App\Controller;

use App\Entity\Environnement;
use App\Entity\Images;
use App\Form\EnvironnementType;
use App\Repository\EnvironnementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/environnement")
 */
class EnvironnementController extends AbstractController
{
    /**
     * @Route("/", name="environnement_home", methods={"GET"})
     */
    public function environnement(EnvironnementRepository $environnementRepository): Response
    {
        return $this->render('environnement/env.html.twig', [
            'environnements' => $environnementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/index", name="environnement_index", methods={"GET"})
     */
    public function index(EnvironnementRepository $environnementRepository): Response
    {
        return $this->render('environnement/index.html.twig', [
            'environnements' => $environnementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="environnement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $environnement = new Environnement();
        $form = $this->createForm(EnvironnementType::class, $environnement);
        $form->handleRequest($request);

        $images = $form->get('images')->getData();

        if ($form->isSubmitted() && $form->isValid()) {

            foreach($images as $image){
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()).'.'.$image->guessExtension();

                // On copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );

                // On crée l'image dans la base de données
                $img = new Images();
                $img->setName($fichier);
                $environnement->addImage($img);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($environnement);
            $entityManager->flush();

            return $this->redirectToRoute('environnement_index');
        }

        return $this->render('environnement/new.html.twig', [
            'environnement' => $environnement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="environnement_show", methods={"GET"})
     */
    public function show(Environnement $environnement): Response
    {
        return $this->render('environnement/show.html.twig', [
            'environnement' => $environnement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="environnement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Environnement $environnement): Response
    {
        $form = $this->createForm(EnvironnementType::class, $environnement);
        $form->handleRequest($request);
        $images = $form->get('images')->getData();

        if ($form->isSubmitted() && $form->isValid()) {
            foreach($images as $image){
                // On génère un nouveau nom de fichier
                $fichier = md5(uniqid()).'.'.$image->guessExtension();

                // On copie le fichier dans le dossier uploads
                $image->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );

                // On crée l'image dans la base de données
                $img = new Images();
                $img->setName($fichier);
                $environnement->addImage($img);
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('environnement_index');
        }

        return $this->render('environnement/edit.html.twig', [
            'environnement' => $environnement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="environnement_delete", methods={"POST"})
     */
    public function delete(Request $request, Environnement $environnement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$environnement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($environnement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('environnement_index');
    }

    /**
     * @Route("/supprime/image/{id}", name="environnement_delete_image", methods={"HEAD","GET","DELETE"})
     */
    public function deleteImage(Images $image, Request $request){
        $data = json_decode($request->getContent(), true);

        // On vérifie si le token est valide

        // On récupère le nom de l'image
        $nom = $image->getName();
        // On supprime le fichier
        unlink($this->getParameter('images_directory').'/'.$nom);

        // On supprime l'entrée de la base
        $em = $this->getDoctrine()->getManager();
        $em->remove($image);
        $em->flush();

        // On répond en json
        return new JsonResponse(['success' => 1]);
    }
}

templates/environnement/_delete_form.html.twig
<form method="post" action="{{ path('environnement_delete', {'id': environnement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ environnement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/environnement/_form.html.twig
{{ form_start(form) }}
<h4>Les champs marqués d'un <span style="color:red">*</span> sont obligatoires</h4>

<div class="container mt-3 form shadow p-3 mb-5 bg-white rounded">
    <div class="row">
        <div class="col-8">
            {{ form_label(form.Title) }}
            {{ form_widget(form.Title) }}
            {{ form_errors(form.Title) }}
        </div>
    </div>
    <br>
    <br>
    <p><strong>Choisissez votre destination dans le menu déroulant.</strong></p>
    <div class="row">
        <div class="col-8">
            <div class="d-flex">
                {{ form_label(form.Region) }}
                <p style="color:red">*</p>
            </div>
            {{ form_widget(form.Region) }}
            {{ form_errors(form.Region) }}
        </div>
    </div>
    <br>
    <br>
    <p><strong>Que souhaitez vous faire durant votre séjour.</strong></p>
    <div class="row">
        <div class="col-8">
            <div class="d-flex">
                {{ form_label(form.Theme) }}
                <p style="color:red">*</p>
            </div>
            {{ form_widget(form.Theme) }}
            {{ form_errors(form.Theme) }}
    <br>
    <br>

        </div>
    </div>

    <p><strong>Décrivez en quelques lignes l'endroit où vous souhaiteriez vous installer, les mots clefs aideront à faciliter votre recherche.</strong></p>

    <div class="row">
        <div class="col-8">
    <div class="d-flex">
        {{ form_label(form.Description) }}
        <p style="color:red">*</p>
    </div>
    {{ form_widget(form.Description) }}
    {{ form_errors(form.Description) }}
    <br>
        </div>
    </div>

    <div class="row">
        <div class="col-8">
            {{ form_label(form.Adresse) }}
            {{ form_widget(form.Adresse) }}
            {{ form_errors(form.Adresse) }}
            {{ form_help(form.Adresse) }} 
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-8">
            {{ form_label(form.Number_phone) }}
            {{ form_widget(form.Number_phone) }}
            {{ form_errors(form.Number_phone) }} 
            {{ form_help(form.Number_phone) }} 
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-8">
            <p>Sélectionner une image :</p>
            <div class="form-group">
                {{ form_label(form.images) }}
                {{ form_widget(form.images) }}
                {{ form_errors(form.images) }}
                {{ form_help(form.images) }}
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-8">
            <p>Sélectionner des options disponibles :</p>
            <div class="form-group">
                {{ form_label(form.Options) }}
                {{ form_widget(form.Options) }}
                {{ form_errors(form.Options) }}
            </div>
        </div>
    </div>
    <br>

<br>
<button class="btn btn-outline-success"><i class="ri-send-plane-line"></i> {{ button_label|default('Publier') }}</button>
<a href="{{ path('environnement_index') }}" class="btn btn-outline-info"><i class="ri-home-2-line"></i> Retour à l'accueil</a>
    </div>

{% if app.request.attributes.get('_route') == 'host_edit' %}
    <h2>Images</h2>
    {% for image in environnement.images %}
        <div>
            <img src="{{ asset('/uploads/'~image.name) }}" alt="" width="150">


            <a href="{{ path('host_delete_image', {id: image.id})}}" data-delete data-token="{{ csrf_token('delete' ~ image.id )}}">Supprimer</a>
        </div>
    {% endfor %}
{% endif %}
{{ form_end(form) }}

templates/environnement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Environnement{% endblock %}

{% block body %}
    <h1>Edit Environnement</h1>

    {{ include('environnement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('environnement_index') }}">Retour à l'accueil</a>

    {{ include('environnement/_delete_form.html.twig') }}
{% endblock %}

templates/environnement/env.html.twig
{% extends 'base.html.twig' %}

{% block title %}Environnement{% endblock %}

{% block body %}
    <main role="main">
        <div class="jumbotron env_img text-center">
            <div class="container">
            </div>
        </div>
        <div class="album">
            <div class="container">
                <h3>Les lieux à visiter</h3>
                <br>
                <p>Voici une liste de tout les lieux à visiter</p>
                <div class="row">
                    {% for environnement in environnements %}
                        <div class="col-md-4">
                            <div class="card mb-4 shadow-sm">
                                {% for image in environnement.images %}
                                    {% for image in environnement.images %}
                                        <div>
                                            <img src="{{ asset('/uploads/'~image.name) }}" alt="" width="100%">
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                <div class="card-body">
                                    <p class="card-text">{{ environnement.title }}</p>
                                    <hr>
                                    <p class="card-text">{{ environnement.description | slice(0, 350)}}...</p>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a class="btn btn-sm btn-info" href="{{ path('environnement_show', {'id': environnement.id}) }}">Voir</a>
                                        </div>
                                        <small class="text-muted">{{ environnement.region }} / Thème {{ environnement.theme }}</small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </main>
{% endblock %}

templates/environnement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Environnement index{% endblock %}

{% block body %}
    <h1>Environnement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Region</th>
                <th>Theme</th>
                <th>Description</th>
                <th>Adresse</th>
                <th>Number_phone</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for environnement in environnements %}
            <tr>
                <td>{{ environnement.id }}</td>
                <td>{{ environnement.Title }}</td>
                <td>{{ environnement.Region }}</td>
                <td>{{ environnement.Theme }}</td>
                <td>{{ environnement.Description }}</td>
                <td>{{ environnement.Adresse }}</td>
                <td>{{ environnement.NumberPhone }}</td>
                <td>
                    <a href="{{ path('environnement_show', {'id': environnement.id}) }}">show</a>
                    <a href="{{ path('environnement_edit', {'id': environnement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('environnement_new') }}">Create new</a>
{% endblock %}

templates/environnement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Environnement{% endblock %}

{% block body %}
    <h1>Créer une nouvelle recherche</h1>

    {{ include('environnement/_form.html.twig') }}


{% endblock %}

templates/environnement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Environnement{% endblock %}

{% block body %}
    <header class="masthead">
        <div class="intro-body">
            <div class="container col-12 d-flex flex-column align-items-center">
                <div class="card shadow p-3 mb-5 bg-white rounded" style="width: 60vw;">
                    {% for image in environnement.images %}
                        {% for image in environnement.images %}
                            <img class="card-img-top" src="{{ asset('/uploads/'~image.name) }}" alt="Card image cap">
                        {% endfor %}
                    {% endfor %}
                    <div class="card-body">
                        <h3>{{ environnement.Title }}</h3>
                        <br>
                        {% if environnement.Options.ElectricalCharge == true %}<h5 style="color: green"><i class="ri-check-double-line"></i>Dispose d'une borne de recharge pour véhicules électriques</h5>{% endif %}
                        <br>
                        <hr>
                        <br>
                        <p> Dans la région {{ environnement.Region }} {% if environnement.Adresse != NULL %}: {{ environnement.Adresse }}{% endif %}</p>
                        <h5>{{ environnement.Theme }}</h5>
                        <hr>
                        <h4>Description :</h4>
                        <p class="card-text">{{ environnement.Description }}</p>
                        <hr>
                        {% if  environnement.NumberPhone != NULL%}
                        <h4>Téléphone :</h4>
                        <p class="card-text">{{ environnement.NumberPhone }}</p>
                        <hr>
                        {% endif %}
                        <div col-6>
                            <h4>Options disponibles :</h4>
                            <p {% if environnement.Options.Animals == false %}class="false"{% endif %}>Animaux acceptés</p>
                            <p {% if environnement.Options.Barbecue == false %}class="false"{% endif %}>Barbecue</p>
                            <p {% if environnement.Options.Electricity == false %}class="false"{% endif %}>Électricité</p>
                            <p {% if environnement.Options.SwimmingPool == false %}class="false"{% endif %}>Piscine</p>
                            <p {% if environnement.Options.WashingMachine == false %}class="false"{% endif %}>Lave-linge</p>
                            <p {% if environnement.Options.Dryer == false %}class="false"{% endif %}>Sèche-linge</p>
                            <p {% if environnement.Options.Wardrobe == false %}class="false"{% endif %}>Etendoir</p>
                            <p {% if environnement.Options.Toilet1 == false %}class="false"{% endif %}>Toilettes indépendantes</p>
                            <p {% if environnement.Options.Toilet2 == false %}class="false"{% endif %}>Toilettes (chez l’habitant)</p>
                            <p {% if environnement.Options.IndependentShower == false %}class="false"{% endif %}>Douche indépendante</p>
                            <p {% if environnement.Options.ShowerAtHome == false %}class="false"{% endif %}>Douche (chez l’habitant)</p>
                            <p {% if environnement.Options.KitchenAtHome == false %}class="false"{% endif %}>Cuisine (chez l’habitant)</p>
                            <p {% if environnement.Options.IndependentKitchen == false %}class="false"{% endif %}>Cuisine indépendante</p>
                            <p {% if environnement.Options.IndependentRefrigerator == false %}class="false"{% endif %}>Réfrigérateur indépendant</p>
                            <p {% if environnement.Options.RefrigeratorAtHome == false %}class="false"{% endif %}>Réfrigérateur (chez l’habitant)</p>
                            <p {% if environnement.Options.PermittedNaturism == false %}class="false"{% endif %}>Naturisme autorisé</p>
                            <p {% if environnement.Options.PrivateParking == false %}class="false"{% endif %}>Parking privé</p>
                            <p {% if environnement.Options.GardenTable == false %}class="false"{% endif %}>Table de jardin</p>
                            <p {% if environnement.Options.PermittedCampfire == false %}class="false"{% endif %}>Feu de camp autorisé</p>
                            <p {% if environnement.Options.EnclosedTerrain == false %}class="false"{% endif %}>Terrain clos</p>
                            <p {% if environnement.Options.TrainOrBus == false %}class="false"{% endif %}>Train ou Bus</p>
                            <p {% if environnement.Options.Shops == false %}class="false"{% endif %}>Commerces</p>
                            <p {% if environnement.Options.WaterDischarges == false %}class="false"{% endif %}>Rejet des eaux usées</p>
                            <p {% if environnement.Options.ChildrensGames == false %}class="false"{% endif %}>Jeux pour enfants</p>
                            <p {% if environnement.Options.HandicappedAccess == false %}class="false"{% endif %}>Accès handicapé</p>
                            <p {% if environnement.Options.IndependentAccess == false %}class="false"{% endif %}>Accès indépendant</p>
                            <p {% if environnement.Options.DrinkingWater == false %}class="false"{% endif %}>Eau potable</p>
                            <p {% if environnement.Options.ElectricalCharge == false %}class="false"{% endif %}>Station de recharge pour véhicule</p>
                            <p {% if environnement.Options.Internet == false %}class="false"{% endif %}>Internet sans fil</p>

                        </div>
                    </div>
                    <a href="{{ path('environnement_home') }}"><i class="ri-arrow-left-line"></i>Retourner à la liste</a>
                </div>
            </div>
            {% if is_granted('ROLE_ADMIN') %}
                <a class="btn btn-info" href="{{ path('environnement_edit', {'id': environnement.id}) }}">edit</a>
                {{ include('environnement/_delete_form.html.twig') }}
            {% endif %}
        </div>
    </header>
{% endblock %}